### PR TITLE
Fix for ISO 8601 milisconds precision

### PR DESCRIPTION
**Pull request by silviucpp**
Should fix :

https://github.com/Ubiquiti-Cloud/tic/issues/6
https://github.com/Ubiquiti-Cloud/tic/issues/7

Silviu

### CODE REVIEW

**Comment by AeroNotix** [comment]
thanks for this, reviewing.

**Comment by silviucpp** [comment]
Any feedback ?

**Comment by AeroNotix** [comment]
Can you add some tests wherever they are missing?

**Comment by silviucpp** [comment]
Yes of course. should be simple because I added into the bug description the input that fails for both bugs.

**Pull request merged**
